export enum Permissao {
  PRODUTO_VISUALIZAR = 'PRODUTO_VISUALIZAR',
  PRODUTO_CRIAR = 'PRODUTO_CRIAR',
  PRODUTO_EDITAR = 'PRODUTO_EDITAR',
  PRODUTO_INATIVAR = 'PRODUTO_INATIVAR',
  CLIENTE_VISUALIZAR = 'CLIENTE_VISUALIZAR',
  CLIENTE_CRIAR = 'CLIENTE_CRIAR',
  CLIENTE_EDITAR = 'CLIENTE_EDITAR',
  CLIENTE_EXCLUIR = 'CLIENTE_EXCLUIR',
  VENDA_VISUALIZAR = 'VENDA_VISUALIZAR',
  VENDA_CRIAR = 'VENDA_CRIAR',
  USUARIO_GERENCIAR = 'USUARIO_GERENCIAR'
}
